export const GET_TOTAL_SF_DATA = 'GET_TOTAL_SF_DATA';
export const GET_EQUITY_INVESTED_DATA = 'GET_EQUITY_INVESTED_DATA';
export const GET_OCCUPANCY_RATE_DATA = "GET_OCCUPANCY_RATE_DATA";
export const GET_DEAL_WISE_PERFORMANCE = "GET_DEAL_WISE_PERFORMANCE";
export const GET_SOLD_DEALS_DATA = "GET_SOLD_DEALS_DATA";
export const GET_ONGOING_DEALS_DATA = "GET_ONGOING_DEALS_DATA";

export const GET_FUND_WISE_HIGHLIGHT = "GET_FUND_WISE_HIGHLIGHT";
export const GET_CAPITAL_AMOUNT_COMPARISON = "GET_CAPITAL_AMOUNT_COMPARISON";
export const GET_CONTRIBUTION_DISTRIBUTION_COMPARISON = "GET_CONTRIBUTION_DISTRIBUTION_COMPARISON";
export const GET_ASSET_SUMMARY_DATA = "GET_ASSET_SUMMARY_DATA";
export const GET_DEBT_SUMMARY_DATA = "GET_DEBT_SUMMARY_DATA";