import * as actionType from './actionTypes';
import Axios from 'axios';
import { API_URL } from '../../constants/api';

export const getFilteredProperties = query => (dispatch) => {
    let data = { "top": 10, "propertyName": [{ "propertyDisplayName": "Centerra", "propertyId": "71" }, { "propertyDisplayName": "City Center", "propertyId": "77" }, { "propertyDisplayName": "Pacific Center", "propertyId": "313" }, { "propertyDisplayName": "5555 Park Center", "propertyId": "400" }, { "propertyDisplayName": "Parkway logistics Center", "propertyId": "1592" }], "success": true, "version": 1, "message": null };
    dispatch({
        type: actionType.GET_FILTERED_PROPERTIES,
        payload: data
    })
}

export const getPropertyTrackerDetails = query => (dispatch) => {
    let data = null;
    dispatch({
        type: actionType.GET_PROPERTY_TRACKER_DETAILS,
        payload: data
    })
}

export const getPropertyDetails = query => (dispatch) => {
    let data = {
        "property": [{
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Location",
            "attributeValue": "Denver,CO",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Text",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Partner",
            "attributeValue": "SRP Fund A",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 2,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Text",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Year Built",
            "attributeValue": "2017",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 3,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Year",
            "attributeListKey": 1,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "BuildingNRA",
            "attributeValue": "161,671",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 4,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Number",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "AcquisitionDate",
            "attributeValue": "2015-03-03",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Date",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Year Renovated",
            "attributeValue": "",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 6,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Year",
            "attributeListKey": 2,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Underwritten Hold Period",
            "attributeValue": "60 Months",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 7,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Month",
            "attributeListKey": 3,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Months Owned",
            "attributeValue": "59 Months",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 8,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Month",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Current Leased %",
            "attributeValue": "94%",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 9,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Percent",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Date Sold",
            "attributeValue": "",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 1,
            "categoryName": "GENERAL ASSET SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 20,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Date",
            "attributeListKey": 25,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Rental Revenue",
            "attributeValue": null,
            "actualBegin": 650322.95,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 11115,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "REVENUES",
            "categoryGroup": "NOI",
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 1,
            "categoryGroupSortOrder": 1,
            "dateId": 20200201,
            "accountDescription": "Rental Revenue",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 28
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Abatement",
            "attributeValue": null,
            "actualBegin": -5476,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 120,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "REVENUES",
            "categoryGroup": "NOI",
            "attributeSortOrder": 2,
            "categoryTypeSortOrder": 1,
            "categoryGroupSortOrder": 1,
            "dateId": 20200201,
            "accountDescription": "Abatement",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 1
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Recovery Income",
            "attributeValue": null,
            "actualBegin": 28959.26,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 121,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "REVENUES",
            "categoryGroup": "NOI",
            "attributeSortOrder": 3,
            "categoryTypeSortOrder": 1,
            "categoryGroupSortOrder": 1,
            "dateId": 20200201,
            "accountDescription": "Recovery Income",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 26
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Other Income",
            "attributeValue": null,
            "actualBegin": 50611,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "REVENUES",
            "categoryGroup": "NOI",
            "attributeSortOrder": 4,
            "categoryTypeSortOrder": 1,
            "categoryGroupSortOrder": 1,
            "dateId": 20200201,
            "accountDescription": "Other Income",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 22
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Recoverable",
            "attributeValue": null,
            "actualBegin": 71507.61,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "EXPENSES",
            "categoryGroup": "NOI",
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 2,
            "categoryGroupSortOrder": 1,
            "dateId": 20200201,
            "accountDescription": "Recoverable",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 25
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Non-Recoverable",
            "attributeValue": null,
            "actualBegin": 6098.86,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "EXPENSES",
            "categoryGroup": "NOI",
            "attributeSortOrder": 6,
            "categoryTypeSortOrder": 2,
            "categoryGroupSortOrder": 1,
            "dateId": 20200201,
            "accountDescription": "Non-Recoverable",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 20
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Interest Expense",
            "attributeValue": null,
            "actualBegin": 77066,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "DEBT SERVICE",
            "categoryGroup": "DEBT",
            "attributeSortOrder": 8,
            "categoryTypeSortOrder": 3,
            "categoryGroupSortOrder": 2,
            "dateId": 20200201,
            "accountDescription": "Interest Expense",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 14
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Principal Reductions",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 33,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "DEBT SERVICE",
            "categoryGroup": "DEBT",
            "attributeSortOrder": 9,
            "categoryTypeSortOrder": 3,
            "categoryGroupSortOrder": 2,
            "dateId": 20200201,
            "accountDescription": "Principal Reductions",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 1,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 23
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Tenant Improvements",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 44,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "CAPITAL AND LEASING COSTS",
            "categoryGroup": "LEASING COSTS",
            "attributeSortOrder": 10,
            "categoryTypeSortOrder": 4,
            "categoryGroupSortOrder": 3,
            "dateId": 20200201,
            "accountDescription": "Tenant Improvements",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 31
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Leasing Commissions",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "CAPITAL AND LEASING COSTS",
            "categoryGroup": "LEASING COSTS",
            "attributeSortOrder": 11,
            "categoryTypeSortOrder": 4,
            "categoryGroupSortOrder": 3,
            "dateId": 20200201,
            "accountDescription": "Leasing Commissions",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 15
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Capital Improvements",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 2,
            "categoryName": "OPERATING SUMMARY",
            "categoryType": "CAPITAL AND LEASING COSTS",
            "categoryGroup": "LEASING COSTS",
            "attributeSortOrder": 12,
            "categoryTypeSortOrder": 4,
            "categoryGroupSortOrder": 3,
            "dateId": 20200201,
            "accountDescription": "Capital Improvements",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 3
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "ProForma Disposition Date",
            "attributeValue": "Dec 2019",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 3,
            "categoryName": "REVERSION SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Date",
            "attributeListKey": 4,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "ProForma Disposition Month",
            "attributeValue": "Month 60",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 3,
            "categoryName": "REVERSION SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 2,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Month",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "ProForma Estimated Sales Price",
            "attributeValue": "$42,013,600",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 3,
            "categoryName": "REVERSION SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 3,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 5,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "ProForma Est.Sales Price PSF",
            "attributeValue": "$259.87",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 3,
            "categoryName": "REVERSION SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 4,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "ProForma Residual Cap Rate",
            "attributeValue": "10.00%",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 3,
            "categoryName": "REVERSION SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Percent",
            "attributeListKey": 6,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "ProForma Deal IRR",
            "attributeValue": "21.63%",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 3,
            "categoryName": "REVERSION SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 6,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Percent",
            "attributeListKey": 7,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "ProForma Return Multiple",
            "attributeValue": "2.25x",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 3,
            "categoryName": "REVERSION SUMMARY",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 7,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 1,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Factor",
            "attributeListKey": 8,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Purchase Price",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 4,
            "categoryName": "CURRENT COST BASIS",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Purchase Price",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 24
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Acquisition & Loan Costs",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 4,
            "categoryName": "CURRENT COST BASIS",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 2,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Acquisition & Loan Costs",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 2
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Renovation Capital Costs",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 4,
            "categoryName": "CURRENT COST BASIS",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 3,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Renovation Capital Costs",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 27
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Leasing Costs & Improvements",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 4,
            "categoryName": "CURRENT COST BASIS",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 4,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Leasing Costs & Improvements",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 16
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Equipment",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 4,
            "categoryName": "CURRENT COST BASIS",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Equipment",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 10
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Carry Cost",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 4,
            "categoryName": "CURRENT COST BASIS",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 6,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Carry Cost",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 5
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Total CURRENT COST BASIS",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 4,
            "categoryName": "CURRENT COST BASIS",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 30,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Loan Balance",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 5,
            "categoryName": "CURRENT CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Loan Balance",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 35
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Capital Invested with Cash Flow",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 5,
            "categoryName": "CURRENT CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 4,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Capital Invested with Cash Flow",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 4
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Distributions",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 5,
            "categoryName": "CURRENT CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Distributions",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 8
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Distributions",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 5,
            "categoryName": "CURRENT CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Distributions",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 33
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Net Current Assets",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 285481.38,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 5,
            "categoryName": "CURRENT CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 6,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Net Current Assets",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 18
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Total CURRENT CAPITALIZATION",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 285481.38,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 5,
            "categoryName": "CURRENT CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 30,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Loan Balance",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 7,
            "categoryName": "ESTIMATED FULLY FUNDED CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Loan Balance",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 35
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "SRP Fund A Equity",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 7,
            "categoryName": "ESTIMATED FULLY FUNDED CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 2,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "SRP Fund A Equity",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 29
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Stream Equity",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 7,
            "categoryName": "ESTIMATED FULLY FUNDED CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 3,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Stream Equity",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 30
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Distributions",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 7,
            "categoryName": "ESTIMATED FULLY FUNDED CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 4,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Distributions",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 8
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Distributions",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 7,
            "categoryName": "ESTIMATED FULLY FUNDED CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 4,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Distributions",
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 1,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 33
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Capital Invested with Cash Flow",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 7,
            "categoryName": "ESTIMATED FULLY FUNDED CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": "Capital Invested with Cash Flow",
            "editAttribute": 2,
            "editActuals": 1,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 4
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Total Est Fully Funded Capitalization",
            "attributeValue": null,
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 7,
            "categoryName": "ESTIMATED FULLY FUNDED CAPITALIZATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 10,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Lender",
            "attributeValue": "CIBC",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Lender",
            "attributeValue": "Voya",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 1,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Current Effective Interest Rate",
            "attributeValue": "4.75%",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 2,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Current Effective Interest Rate",
            "attributeValue": "6.6619%",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 2,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Spread over 1-Month LIBOR (bps)",
            "attributeValue": "+0 bps",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 3,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Spread over 1-Month LIBOR (bps)",
            "attributeValue": "+500 bps",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 3,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Debt Terms (Years)",
            "attributeValue": "1 Years",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Debt Terms (Years)",
            "attributeValue": "4 Years",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 5,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Extension",
            "attributeValue": " + 1, + 1, + 1",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 6,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Extension",
            "attributeValue": "N/A",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 6,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Maturity",
            "attributeValue": "Dec 2019",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 7,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Maturity",
            "attributeValue": "Jan 2021",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 7,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Amortization",
            "attributeValue": "30 Years",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 8,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Amortization",
            "attributeValue": "FULL I/O",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 8,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Date on Which Amortization Begins",
            "attributeValue": "Jan 2020",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 9,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        },
        {
            "propertyDisplayName": "Centerra",
            "dwPropertyName": "SRPF A/Centerra, LLC",
            "attributeName": "Date on Which Amortization Begins",
            "attributeValue": "N/A",
            "actualBegin": 0,
            "actualMTD": 0,
            "budget": 0,
            "budgetBegin": 0,
            "proforma": 0,
            "amountPSF": 0,
            "categoryKey": 8,
            "categoryName": "DEBT INFORMATION",
            "categoryType": null,
            "categoryGroup": null,
            "attributeSortOrder": 9,
            "categoryTypeSortOrder": 0,
            "categoryGroupSortOrder": 0,
            "dateId": 20200201,
            "accountDescription": null,
            "editAttribute": 2,
            "editActuals": 2,
            "editBudget": 2,
            "editProforma": 2,
            "dataFormat": "Currency",
            "attributeListKey": 0,
            "acctDescriptionKey": 0
        }
        ],
        "success": true,
        "version": 1,
        "message": null
    };
    dispatch({
        type: actionType.GET_PROPERTY_DETAILS,
        payload: data
    })
}

export const getAllManualEditFields = query => (dispatch) => {
    let data = {
        "propertyEditableFields": [{
            "attributeName": "Underwritten Hold Period",
            "categoryKey": 1,
            "dataType": "Month",
            "attributeListKey": 3,
            "attributeKey": 11
        }, {
            "attributeName": "ProForma Disposition Date",
            "categoryKey": 3,
            "dataType": "Date",
            "attributeListKey": 4,
            "attributeKey": 12
        }, {
            "attributeName": "ProForma Estimated Sales Price",
            "categoryKey": 3,
            "dataType": "Currency",
            "attributeListKey": 5,
            "attributeKey": 13
        }, {
            "attributeName": "ProForma Deal IRR",
            "categoryKey": 3,
            "dataType": "Percent",
            "attributeListKey": 7,
            "attributeKey": 15
        }, {
            "attributeName": "ProForma Return Multiple",
            "categoryKey": 3,
            "dataType": "Factor",
            "attributeListKey": 8,
            "attributeKey": 16
        }, {
            "attributeName": "Commited Equity",
            "categoryKey": 14,
            "dataType": "Currency",
            "attributeListKey": 23,
            "attributeKey": 173
        }, {
            "attributeName": "ProForma Residual Cap Rate",
            "categoryKey": 3,
            "dataType": "Percent",
            "attributeListKey": 6,
            "attributeKey": 868
        }, {
            "attributeName": "Year Built",
            "categoryKey": 1,
            "dataType": "Year",
            "attributeListKey": 1,
            "attributeKey": 879
        }],
        "success": true,
        "version": 1,
        "message": null
    };
    dispatch({
        type: actionType.GET_ALL_MANUAL_EDIT_FIELDS,
        payload: data
    })
}

export const saveEditedData = query => (dispatch) => {
    let data = null;
    dispatch({
        type: actionType.SAVE_EDITED_DATA,
        payload: data
    })
}
