export const GET_FILTERED_PROPERTIES = 'GET_FILTERED_PROPERTIES';
export const GET_PROPERTY_TRACKER_DETAILS = 'GET_PROPERTY_TRACKER_DETAILS';
export const GET_PROPERTY_DETAILS = 'GET_PROPERTY_DETAILS';
export const GET_ALL_MANUAL_EDIT_FIELDS = "GET_ALL_MANUAL_EDIT_FIELDS";
export const SAVE_EDITED_DATA = "SAVE_EDITED_DATA";